sudo: required
services:
- docker
language: node_js
node_js:
- '8'
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - GH_REPO=moisbo/sails-hook-redbox-omero
  - GIT_NAME=DeploymentBot
  - GIT_EMAIL=deploy@travis-ci.org
  - secure: tJsMqyE6njnIUCQfXLJGxFWdmmyRPjZD8EqEza7u4DC1cuG0ofWwotVfU0gmDTM2orQ+GV5VXOfsxkHvDMsuYhIKTPAsLHxax4Y/bBTr1ht0TV8xLxvefThFBtY7kPBSCpVz/yZoEujKjK9/mA7chRqyMIDFb69mO4kR/+bMD8aNdeQzHQOz0ZBF4TSGVHQUTBmQhsrGgZIZ7wmDAR79bQhA//hQbFsZ0reQK17ZrSuoI6QtkhRl02Vq+e8jEvAttUUWDkTI4R5i06tagV+7+mpbszFYq0FKu3L+MiXvsjPgSlvmjfBA8tRZzDungEfe4I2Kh55+cm6zPESPeC2sFM1oGubB1ybDhp2FMowrrK1Az1zVmXeDQVjLPcnUA713TG03aJlqHjExXjTKpTbUlP6qeC4XRQ38SCOrbgNsgIk2h66jeQHZLdCxS2g6R0+gFIpKZ0DbrxOU39LprQ1as+/5TsRKUsqaHBt0X+dsMhzLYZpe+j/C8gq3CDt1JRoVYlHO1iGya4qXjdOcpqkOnZmB0yefmmIemds1S+CZYEPwdzsL/xaEgTC6FOXj2yvhE5z2brl6RmtiWIJtq/pzzTcQSUiqsNAUvP6byTr0aHJD9r1tA2BZwWwpttDCpmzVGrGd2bjLL3YiXoM0+fJfSsLtuhvNpKDk+HRqANy7hao=
install:
- npm install; cd app/omero; npm install; chmod +x buildAngularProd.sh; ./buildAngularProd.sh;
  cd -;
script: true
after_success:
- chmod +x deploySnapshotToBranch.sh; ./deploySnapshotToBranch.sh
